# Generated by Django 3.2.12 on 2023-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/properties/'),
        ),
    ]
