# Generated by Django 3.2.12 on 2023-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listingvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/properties/'),
        ),
    ]
