# Generated by Django 3.2.12 on 2023-07-18 13:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=255)),
                ('listing', models.CharField(max_length=255)),
                ('locaction', models.CharField(max_length=255)),
                ('user_id', models.PositiveIntegerField(blank=True)),
                ('user_slug', models.CharField(blank=True, max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Contacted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
